# Generated by Django 5.2 on 2025-06-13 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_monthlyemotionstat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyEmotionStat',
        ),
    ]
