# Generated by Django 5.2 on 2025-05-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_name_remove_review_user_review_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(blank=True, default='Аноним', max_length=100),
        ),
    ]
