# Generated by Django 5.2 on 2025-05-12 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без названия', max_length=200)),
                ('content', models.TextField(default='')),
                ('html_content', models.TextField(default='')),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('font_size', models.CharField(default='16px', max_length=10)),
                ('text_align', models.CharField(default='left', max_length=10)),
                ('is_bold', models.BooleanField(default=False)),
                ('is_underline', models.BooleanField(default=False)),
                ('is_strikethrough', models.BooleanField(default=False)),
                ('list_type', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='entries/covers/')),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
