# Generated by Django 5.2.1 on 2025-05-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_hashtags_entry_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='html_content',
        ),
    ]
